### ISSUE TITLE
set the server host IP and port 

### ISSUE THREAD

**Issue by nicolas-busca** [gietema/clusterfun#151]
**Is your feature request related to a problem? Please describe.**
When running clusterfun on a remote server I'd like to be able to access directly the app via the host IP (or domain) on a specified port. It's really annoying to have to open a tunnel every time :-)

**Describe the solution you'd like**
Set the host IP or domain and port when running the server (like clt.scatter(... host='my.pretty.host', port=31416)

**Describe alternatives you've considered**
I'm aware that a current workaround is to access the app opening an ssh tunnel.

**Comment by nicolas-busca** [comment]
it looks like i can specify the port via CLUSTERFUN_PORT, but I haven't seen an option to specify the port

**Comment by nicolas-busca** [comment]
It works as I expect if I set `host="0.0.0.0"` in the uvicorn config in `clusterfun/plot.py`

**Comment by gietema** [comment]
Thanks, good idea. I can add the host as an environment variable as well - that should solve it?

**Comment by nicolas-busca** [comment]
> Thanks, good idea. I can add the host as an environment variable as well - that should solve it?

yes! definitely, thanks!

**Comment by gietema** [comment]
@nicolas-busca Ok, I hope this works and thanks for raising this! Please open an issue if you encounter anything that's not working, happy to fix it!

**Comment by nicolas-busca** [comment]
FYI I've tested it and works!
